name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.26'
      - run: cpanm --installdeps .
      - run: prove -lv t
